server:
  port: 80

#配置链路追踪地址
spring:
  zipkin:
    base-url: http://192.168.160.100:9411/
    sender:
      type: web

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: product_route #以 /admin/product 开头的所有请求都lb转给service-product
          uri: lb://service-product
          predicates: #断言
            - Path=/admin/product/**


