server:
  port: 80

#配置链路追踪地址
spring:
  zipkin:
    base-url: http://192.168.160.100:9411/
    sender:
      type: web

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许所有地址来源跨域
            allowedMethods: "*" #允许所有求情方式跨域
            allowedHeaders: "*" #负责跨域的原因就是因为带有一些负责的请求头
            allowCredentials: true #允许带一些安全标志跨域 比如：Cookie
      routes:
        - id: product_route #以 /admin/product 开头的所有请求都lb转给service-product
          uri: lb://service-product
          predicates: #断言
            - Path=/admin/product/**


